# permissions for end users to view sleeps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sleep-viewer-role
rules:
- apiGroups:
  - inflion.inflion.com
  resources:
  - sleeps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inflion.inflion.com
  resources:
  - sleeps/status
  verbs:
  - get
