# permissions for end users to edit sleeps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sleep-editor-role
rules:
- apiGroups:
  - inflion.inflion.com
  resources:
  - sleeps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inflion.inflion.com
  resources:
  - sleeps/status
  verbs:
  - get
